copy:
    cp paper.md ../../markdown-paper/paperSE.md;
pdf:
        pandoc --filter pandoc-citeproc --bibliography=references.bib --variable classoption=twocolumn --variable papersize=a4paper -s paper.md -o paper.pdf
